### ISSUE TITLE
这个项目就我来维护吧

### ISSUE THREAD

**Issue by XYCode-Kerman** [YiriMiraiProject/YiriMirai#56]
我是这个框架的老用户了，其他框架都用不惯，结果作者停更了（悲）

**Comment by Wybxc** [comment]
很感谢╰(*°▽°*)╯

可以先完成对 mirai-api-http 高版本的适配，然后提交 pr

**Comment by Wybxc** [comment]
遇到问题可以从 QQ 群里联系我

**Comment by XYCode-Kerman** [comment]
好的，最近有点忙，我尽量抽时间(ฅ´ω`ฅ)
